version: "3.9"
services:
  app:
    image: go-api-experiment
    build:
      args:
        target: dev
    volumes:
      - .:/go/src/app
    ports:
      - "11323:1323"
    depends_on:
      - db
  db:
    image: mysql:8.0.33
    container_name: go-api-experiment-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-api-experiment-local
      MYSQL_USER: local-user
      MYSQL_PASSWORD: local-password
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
  redis:
    image: redis:7.0.11
    container_name: go-api-experiment-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
